### ISSUE TITLE
[Bug] Link labels centering & tooltip

### ISSUE THREAD

**Issue by 1earch** [ChrisYounger/flow_map_viz#1] opened 2020-02-24 11:04 UTC
Hello @ChrisYounger,

Many thanks for this really usefull vizualisation for Splunk! 🙂 

Creating a dashboard, we detected two bugs (see image below):
1. Link labels aren't perfectly centered on line
2. Link labels have a fixed `200px` width (highlighted in purple on the screenshot below) which causes a problem when displaying the tooltip because the ones behind aren't accessible.

![image](https://user-images.githubusercontent.com/1888635/75146842-3a6a1700-56fc-11ea-9fd2-8f6565fde2df.png)

I have a fix and I will propose you a PR soon.

Regards

**Comment by ChrisYounger** [comment] 2020-02-28 08:58
Hi 1earch.
Thank you so much for providing this bug report and pull request.  

1. Unfortunately changing this alignment would break dashboards for people who are already using this visualization.  It is also by design that the label appears slightly above the line, because this looks better in the default use-case if there is a small label and the line is going horizontally. Perhaps in hindsight this was a poor decision by me.  If you want to bump the label down then you can either do a CSS override (by putting a style tag in your dashboard source code) or you can supply a "labely" column in your data, with a value like "8" or something that will push the label down.

2. Your pull request was a good fix for this problem with no backward compatibility problems. I have made some slight changes to the code you supplied and merged it. I will get it to splunkbase soon.

Regards, Chris.

**Closed as completed by ChrisYounger** 2020-02-28 08:58 UTC
